apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vms.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: VM
    plural: vms
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
